# -*- coding: utf-8 -*-
"""clases.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1au7eQHcyFbkoA7J9CCq-WPtylZYZysV8
"""

print("hola mundo")

!python --version

#Variables Globales
palabra = "Hola Mundo"
#Ejecucion
print (palabra[0:4])
for letra in enumerate(palabra): print(letra)
matriz= [letra for letra in palabra]
print (matriz)
matriz2 = [uno for uno in str.split(palabra)]
print(matriz2)
#segundo ejercicio
precio = [200,100,300]
cantidad = [2]
nueva = [preciounitario*1.13 for preciounitario in precio]
nueva2 = [cant*prec for cant in cantidad for prec in precio]
print (nueva)
print (nueva2)
#tercer ejercicio
def sorter(elem):
    return elem[1]
palabras = ["te","tomate","uva","naranja"]
sorted_list = sorted(palabras, key=sorter)
print(sorted_list)
#cuarto ejercicio
ingresos = [500,300,200]
gastos =   [20, 40, 80, 90, 75, 35, 20, 10,25, 60, 300]
totaling = 0
for ingreso in ingresos: totaling = ingreso + totaling
totalgast = 0
for gasto in gastos: totalgast = gasto + totalgast
print("Ingresos= %i Gastos= %i" %(totaling,totalgast))
resultado = totaling - totalgast
print("Resultado= %i" %(resultado))
if resultado > 0:
  print ("Ganancias ", resultado)
#Quinto ejercicio
ingresoscomp = [["Enero",500],["Febrero",300],["Marzo",200], ["Mayo",300]]
gastoscomp =   [["Enero",20],["Febrero",40],["Marzo",80], ["Mayo",300]]